#!/bin/sh

if [ ${PUBKEY:+set} ]; then
  passwd -d git
  printf '%s\n' "$PUBKEY" | install -o git -g git -m 0600 /dev/stdin ~git/.ssh/authorized_keys
fi

if [ ${PASSWD:+set} ]; then
  printf 'git:%s' "$PASSWD" | chpasswd
fi

exec runsvdir /run/runsvdir
